### ISSUE TITLE
Cannot stop service after you run the client program

### ISSUE THREAD

**Issue by ashendes** [ballerina-attic/composer#5027]
The 'Stop' button disappears when you run the client program.

**Steps to reproduce:**
1. Open composer
2. Create a service
3. Create a client program to use the service
3. Run the service
4. Run the client program

**Images:**
![screenshot from 2018-07-04 11-09-02](https://user-images.githubusercontent.com/25567263/42258815-49da8346-7f7b-11e8-9691-7d4bc9468d28.png)

![screenshot from 2018-07-04 11-09-32](https://user-images.githubusercontent.com/25567263/42259041-4c643476-7f7c-11e8-8441-cc1d1997d721.png)

**Comment by nadeeshaan** [comment]
@ashendes Can you check this in the latest master build in the https://github.com/ballerina-platform/ballerina-lang repository? We do not maintain this repository anymore.
